
export const getLanguageFromExtension = (filename: string): string => {
    const ext = filename.split('.').pop()?.toLowerCase() || '';

    const map: Record<string, string> = {
        'js': 'javascript',
        'mjs': 'javascript',
        'cjs': 'javascript',
        'jsx': 'javascript',
        'ts': 'typescript',
        'mts': 'typescript',
        'cts': 'typescript',
        'tsx': 'typescript',
        'py': 'python',
        'ipynb': 'python',
        'json': 'json',
        'jsonc': 'json',
        'html': 'html',
        'htm': 'html',
        'css': 'css',
        'scss': 'scss',
        'sass': 'scss',
        'less': 'less',
        'md': 'markdown',
        'markdown': 'markdown',
        'yaml': 'yaml',
        'yml': 'yaml',
        'xml': 'xml',
        'svg': 'xml',
        'sql': 'sql',
        'sh': 'shell',
        'bash': 'shell',
        'zsh': 'shell',
        'ps1': 'powershell',
        'bat': 'bat',
        'cmd': 'bat',
        'go': 'go',
        'rs': 'rust',
        'java': 'java',
        'c': 'c',
        'h': 'c',
        'cpp': 'cpp',
        'hpp': 'cpp',
        'cc': 'cpp',
        'hh': 'cpp',
        'cs': 'csharp',
        'php': 'php',
        'rb': 'ruby',
        'lua': 'lua',
        'r': 'r',
        'swift': 'swift',
        'kt': 'kotlin',
        'kts': 'kotlin',
        'dart': 'dart',
        'pl': 'perl',
        'pm': 'perl',
        'scala': 'scala',
        'hs': 'haskell',
        'ex': 'elixir',
        'exs': 'elixir',
        'clj': 'clojure',
        'm': 'objective-c',
        'mm': 'objective-c',
        'graphql': 'graphql',
        'gql': 'graphql',
        'proto': 'proto',
        'sol': 'sol',
        'toml': 'toml',
        'ini': 'ini',
        'dockerfile': 'dockerfile',
        'makefile': 'makefile',
        'props': 'ini',
        'config': 'xml',
        'env': 'plaintext',
        'gitignore': 'plaintext',
        'vue': 'html',
        'svelte': 'html',
        'handlebars': 'handlebars',
        'hbs': 'handlebars',
        'pug': 'pug',
        'jade': 'pug',
        'coffee': 'coffeescript',
        'fs': 'fsharp',
        'fsi': 'fsharp',
        'pas': 'pascal',
        'f': 'fortran',
        'f90': 'fortran',
        'scm': 'scheme',
        'lisp': 'lisp',
        'v': 'verilog',
        'vhd': 'vhdl'
    };

    return map[ext] || 'plaintext';
};

export const normalizeLanguage = (lang: string): string => {
    const map: Record<string, string> = {
        'js': 'javascript',
        'ts': 'typescript',
        'py': 'python',
        'sh': 'shell',
        'bash': 'shell',
        'zsh': 'shell',
        'cs': 'csharp',
        'rb': 'ruby',
        'rs': 'rust',
        'yml': 'yaml',
        'tsx': 'typescript',
        'jsx': 'javascript',
        // Add more direct mappings if needed
    };
    return map[lang.toLowerCase()] || lang.toLowerCase();
};
