import { ThemeDefinition, ThemeCategory } from '@shared/types/theme'

function createHsl(h: number, s: number, l: number): string {
    return `${h} ${s}% ${l}%`
}

const ELITE_DARK: ThemeCategory = 'elite-dark'
const VIBRANT_NEON: ThemeCategory = 'vibrant-neon'
const PROFESSIONAL_LIGHT: ThemeCategory = 'professional-light'
const ARTISANAL: ThemeCategory = 'artisanal'

export const BUILTIN_THEMES: ThemeDefinition[] = [
    {
        id: 'graphite',
        name: 'Graphite',
        category: ELITE_DARK,
        isDark: true,
        description: 'A sleek, professional dark theme with blue accents',
        colors: {
            background: createHsl(240, 5, 10),
            foreground: createHsl(0, 0, 98),
            card: createHsl(240, 4, 12),
            cardForeground: createHsl(0, 0, 98),
            popover: createHsl(240, 4, 12),
            popoverForeground: createHsl(0, 0, 98),
            primary: createHsl(210, 100, 50),
            primaryForeground: createHsl(0, 0, 98),
            secondary: createHsl(240, 4, 16),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(240, 4, 16),
            mutedForeground: createHsl(240, 5, 65),
            accent: createHsl(240, 4, 16),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(240, 4, 16),
            input: createHsl(240, 4, 16),
            ring: createHsl(210, 100, 50),
            radius: 1
        }
    },
    {
        id: 'obsidian',
        name: 'Obsidian',
        category: ELITE_DARK,
        isDark: true,
        description: 'Pure black theme with white accents',
        colors: {
            background: createHsl(0, 0, 0),
            foreground: createHsl(0, 0, 98),
            card: createHsl(0, 0, 4),
            cardForeground: createHsl(0, 0, 98),
            popover: createHsl(0, 0, 4),
            popoverForeground: createHsl(0, 0, 98),
            primary: createHsl(0, 0, 98),
            primaryForeground: createHsl(0, 0, 0),
            secondary: createHsl(0, 0, 9),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(0, 0, 9),
            mutedForeground: createHsl(0, 0, 60),
            accent: createHsl(0, 0, 9),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(0, 0, 12),
            input: createHsl(0, 0, 9),
            ring: createHsl(0, 0, 98),
            radius: 1
        }
    },
    {
        id: 'midnight',
        name: 'Midnight',
        category: ELITE_DARK,
        isDark: true,
        description: 'Deep blue themed dark mode',
        colors: {
            background: createHsl(230, 40, 5),
            foreground: createHsl(230, 20, 95),
            card: createHsl(230, 35, 7),
            cardForeground: createHsl(230, 20, 95),
            popover: createHsl(230, 35, 7),
            popoverForeground: createHsl(230, 20, 95),
            primary: createHsl(230, 80, 60),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(230, 30, 10),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(230, 30, 10),
            mutedForeground: createHsl(230, 15, 65),
            accent: createHsl(230, 50, 20),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(230, 25, 15),
            input: createHsl(230, 25, 15),
            ring: createHsl(230, 80, 60),
            radius: 1
        }
    },
    {
        id: 'deep-forest',
        name: 'Deep Forest',
        category: ELITE_DARK,
        isDark: true,
        description: 'Nature-inspired dark theme with green accents',
        colors: {
            background: createHsl(150, 40, 3),
            foreground: createHsl(120, 20, 90),
            card: createHsl(150, 35, 5),
            cardForeground: createHsl(120, 20, 90),
            popover: createHsl(150, 35, 5),
            popoverForeground: createHsl(120, 20, 90),
            primary: createHsl(142, 70, 45),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(150, 30, 7),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(150, 30, 7),
            mutedForeground: createHsl(150, 15, 60),
            accent: createHsl(142, 50, 15),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(150, 20, 12),
            input: createHsl(150, 20, 12),
            ring: createHsl(142, 70, 45),
            radius: 1
        }
    },
    {
        id: 'dracula',
        name: 'Dracula',
        category: ELITE_DARK,
        isDark: true,
        description: 'Popular code editor theme',
        colors: {
            background: createHsl(231, 15, 18),
            foreground: createHsl(60, 30, 96),
            card: createHsl(231, 15, 20),
            cardForeground: createHsl(60, 30, 96),
            popover: createHsl(231, 15, 20),
            popoverForeground: createHsl(60, 30, 96),
            primary: createHsl(265, 89, 78),
            primaryForeground: createHsl(231, 15, 18),
            secondary: createHsl(231, 15, 25),
            secondaryForeground: createHsl(60, 30, 96),
            muted: createHsl(231, 15, 25),
            mutedForeground: createHsl(231, 15, 70),
            accent: createHsl(250, 100, 75),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(231, 15, 35),
            input: createHsl(231, 15, 25),
            ring: createHsl(265, 89, 78),
            radius: 1
        }
    },
    {
        id: 'cyberpunk',
        name: 'Cyberpunk',
        category: VIBRANT_NEON,
        isDark: true,
        description: 'Neon-infused cyber aesthetic',
        colors: {
            background: createHsl(280, 50, 5),
            foreground: createHsl(180, 100, 90),
            card: createHsl(280, 45, 7),
            cardForeground: createHsl(180, 100, 90),
            popover: createHsl(280, 45, 7),
            popoverForeground: createHsl(180, 100, 90),
            primary: createHsl(326, 100, 60),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(280, 40, 10),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(280, 40, 10),
            mutedForeground: createHsl(180, 50, 60),
            accent: createHsl(190, 100, 50),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(320, 100, 50),
            input: createHsl(280, 40, 10),
            ring: createHsl(326, 100, 60),
            radius: 1
        }
    },
    {
        id: 'matrix',
        name: 'Matrix',
        category: VIBRANT_NEON,
        isDark: true,
        description: 'Classic green code aesthetic',
        colors: {
            background: createHsl(120, 100, 2),
            foreground: createHsl(120, 100, 50),
            card: createHsl(120, 100, 3),
            cardForeground: createHsl(120, 100, 50),
            popover: createHsl(120, 100, 3),
            popoverForeground: createHsl(120, 100, 50),
            primary: createHsl(120, 100, 50),
            primaryForeground: createHsl(0, 0, 0),
            secondary: createHsl(120, 100, 5),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(120, 100, 5),
            mutedForeground: createHsl(120, 100, 40),
            accent: createHsl(120, 100, 15),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(120, 100, 20),
            input: createHsl(120, 100, 5),
            ring: createHsl(120, 100, 50),
            radius: 1
        }
    },
    {
        id: 'synthwave',
        name: 'Synthwave',
        category: VIBRANT_NEON,
        isDark: true,
        description: 'Retro-futuristic vaporwave colors',
        colors: {
            background: createHsl(260, 40, 10),
            foreground: createHsl(300, 100, 95),
            card: createHsl(260, 40, 12),
            cardForeground: createHsl(300, 100, 95),
            popover: createHsl(260, 40, 12),
            popoverForeground: createHsl(300, 100, 95),
            primary: createHsl(320, 100, 60),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(260, 40, 15),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(260, 40, 15),
            mutedForeground: createHsl(300, 50, 70),
            accent: createHsl(280, 100, 50),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(190, 100, 50),
            input: createHsl(260, 40, 15),
            ring: createHsl(320, 100, 60),
            radius: 1
        }
    },
    {
        id: 'snow',
        name: 'Snow',
        category: PROFESSIONAL_LIGHT,
        isDark: false,
        description: 'Clean and bright light theme',
        colors: {
            background: createHsl(0, 0, 100),
            foreground: createHsl(240, 10, 3.9),
            card: createHsl(0, 0, 100),
            cardForeground: createHsl(240, 10, 3.9),
            popover: createHsl(0, 0, 100),
            popoverForeground: createHsl(240, 10, 3.9),
            primary: createHsl(240, 5.9, 10),
            primaryForeground: createHsl(0, 0, 98),
            secondary: createHsl(240, 4.8, 95.9),
            secondaryForeground: createHsl(240, 10, 3.9),
            muted: createHsl(240, 4.8, 95.9),
            mutedForeground: createHsl(240, 3.8, 46.1),
            accent: createHsl(240, 4.8, 95.9),
            accentForeground: createHsl(240, 10, 3.9),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(240, 5.9, 90),
            input: createHsl(240, 5.9, 90),
            ring: createHsl(240, 5.9, 10),
            radius: 1
        }
    },
    {
        id: 'sand',
        name: 'Sand',
        category: PROFESSIONAL_LIGHT,
        isDark: false,
        description: 'Warm sandy beige tones',
        colors: {
            background: createHsl(35, 30, 96),
            foreground: createHsl(35, 15, 15),
            card: createHsl(35, 30, 96),
            cardForeground: createHsl(35, 15, 15),
            popover: createHsl(35, 30, 96),
            popoverForeground: createHsl(35, 15, 15),
            primary: createHsl(35, 60, 35),
            primaryForeground: createHsl(35, 30, 96),
            secondary: createHsl(35, 20, 90),
            secondaryForeground: createHsl(35, 15, 15),
            muted: createHsl(35, 20, 90),
            mutedForeground: createHsl(35, 10, 45),
            accent: createHsl(35, 50, 88),
            accentForeground: createHsl(35, 15, 15),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(35, 15, 85),
            input: createHsl(35, 15, 85),
            ring: createHsl(35, 60, 35),
            radius: 1
        }
    },
    {
        id: 'sky',
        name: 'Sky',
        category: PROFESSIONAL_LIGHT,
        isDark: false,
        description: 'Fresh blue sky inspired light theme',
        colors: {
            background: createHsl(200, 40, 98),
            foreground: createHsl(200, 60, 10),
            card: createHsl(200, 40, 98),
            cardForeground: createHsl(200, 60, 10),
            popover: createHsl(200, 40, 98),
            popoverForeground: createHsl(200, 60, 10),
            primary: createHsl(200, 100, 40),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(200, 30, 94),
            secondaryForeground: createHsl(200, 60, 10),
            muted: createHsl(200, 30, 94),
            mutedForeground: createHsl(200, 30, 50),
            accent: createHsl(200, 50, 92),
            accentForeground: createHsl(200, 60, 10),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(200, 40, 88),
            input: createHsl(200, 40, 88),
            ring: createHsl(200, 100, 40),
            radius: 1
        }
    },
    {
        id: 'minimal',
        name: 'Minimal',
        category: PROFESSIONAL_LIGHT,
        isDark: false,
        description: 'Ultra clean minimal light theme',
        colors: {
            background: createHsl(210, 20, 98),
            foreground: createHsl(210, 20, 20),
            card: createHsl(210, 20, 98),
            cardForeground: createHsl(210, 20, 20),
            popover: createHsl(210, 20, 98),
            popoverForeground: createHsl(210, 20, 20),
            primary: createHsl(0, 0, 0),
            primaryForeground: createHsl(0, 0, 100),
            secondary: createHsl(210, 20, 92),
            secondaryForeground: createHsl(210, 20, 20),
            muted: createHsl(210, 20, 92),
            mutedForeground: createHsl(210, 10, 50),
            accent: createHsl(210, 20, 90),
            accentForeground: createHsl(210, 20, 20),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(210, 20, 88),
            input: createHsl(210, 20, 88),
            ring: createHsl(0, 0, 0),
            radius: 1
        }
    },
    {
        id: 'paper',
        name: 'Paper',
        category: PROFESSIONAL_LIGHT,
        isDark: false,
        description: 'Warm off-white like writing paper',
        colors: {
            background: createHsl(40, 20, 92),
            foreground: createHsl(0, 0, 10),
            card: createHsl(40, 20, 92),
            cardForeground: createHsl(0, 0, 10),
            popover: createHsl(40, 20, 92),
            popoverForeground: createHsl(0, 0, 10),
            primary: createHsl(0, 0, 0),
            primaryForeground: createHsl(0, 0, 90),
            secondary: createHsl(40, 15, 88),
            secondaryForeground: createHsl(0, 0, 10),
            muted: createHsl(40, 15, 88),
            mutedForeground: createHsl(40, 10, 40),
            accent: createHsl(0, 0, 85),
            accentForeground: createHsl(0, 0, 10),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(40, 10, 80),
            input: createHsl(40, 10, 80),
            ring: createHsl(0, 0, 0),
            radius: 1
        }
    },
    {
        id: 'ocean',
        name: 'Ocean',
        category: ARTISANAL,
        isDark: true,
        description: 'Deep ocean blues',
        colors: {
            background: createHsl(200, 50, 5),
            foreground: createHsl(200, 40, 95),
            card: createHsl(200, 45, 7),
            cardForeground: createHsl(200, 40, 95),
            popover: createHsl(200, 45, 7),
            popoverForeground: createHsl(200, 40, 95),
            primary: createHsl(190, 100, 50),
            primaryForeground: createHsl(200, 50, 5),
            secondary: createHsl(200, 40, 12),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(200, 40, 12),
            mutedForeground: createHsl(200, 20, 65),
            accent: createHsl(200, 80, 20),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(200, 60, 25),
            input: createHsl(200, 40, 12),
            ring: createHsl(190, 100, 50),
            radius: 1
        }
    },
    {
        id: 'rose',
        name: 'Rose',
        category: ARTISANAL,
        isDark: true,
        description: 'Soft romantic rose tones',
        colors: {
            background: createHsl(340, 30, 10),
            foreground: createHsl(340, 40, 95),
            card: createHsl(340, 25, 12),
            cardForeground: createHsl(340, 40, 95),
            popover: createHsl(340, 25, 12),
            popoverForeground: createHsl(340, 40, 95),
            primary: createHsl(340, 100, 75),
            primaryForeground: createHsl(340, 30, 10),
            secondary: createHsl(340, 20, 15),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(340, 20, 15),
            mutedForeground: createHsl(340, 20, 70),
            accent: createHsl(340, 100, 30),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(340, 60, 40),
            input: createHsl(340, 20, 15),
            ring: createHsl(340, 100, 75),
            radius: 1
        }
    },
    {
        id: 'coffee',
        name: 'Coffee',
        category: ARTISANAL,
        isDark: true,
        description: 'Rich roasted coffee tones',
        colors: {
            background: createHsl(25, 30, 7),
            foreground: createHsl(25, 30, 90),
            card: createHsl(25, 25, 9),
            cardForeground: createHsl(25, 30, 90),
            popover: createHsl(25, 25, 9),
            popoverForeground: createHsl(25, 30, 90),
            primary: createHsl(25, 100, 70),
            primaryForeground: createHsl(25, 30, 7),
            secondary: createHsl(25, 20, 12),
            secondaryForeground: createHsl(0, 0, 98),
            muted: createHsl(25, 20, 12),
            mutedForeground: createHsl(25, 15, 65),
            accent: createHsl(25, 60, 20),
            accentForeground: createHsl(0, 0, 98),
            destructive: createHsl(0, 84, 60),
            destructiveForeground: createHsl(0, 0, 98),
            border: createHsl(25, 40, 30),
            input: createHsl(25, 20, 12),
            ring: createHsl(25, 100, 70),
            radius: 1
        }
    }
]

export function getThemeById(id: string): ThemeDefinition | undefined {
    return BUILTIN_THEMES.find(t => t.id === id)
}

export function getThemesByCategory(category: ThemeCategory): ThemeDefinition[] {
    return BUILTIN_THEMES.filter(t => t.category === category)
}

export function getAllThemeCategories(): ThemeCategory[] {
    return [...new Set(BUILTIN_THEMES.map(t => t.category))]
}

export function getLightThemes(): ThemeDefinition[] {
    return BUILTIN_THEMES.filter(t => !t.isDark)
}

export function getDarkThemes(): ThemeDefinition[] {
    return BUILTIN_THEMES.filter(t => t.isDark)
}
