const plugin = require('tailwindcss/plugin');
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class'],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
    ],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: 'var(--tengra-container-padding)',
            screens: {
                '2xl': 'var(--tengra-container-2xl)',
                '3xl': 'var(--tengra-container-3xl)',
            },
        },
        extend: {
            fontFamily: {
                sans: ['var(--font-sans)', 'Segoe UI', 'Segoe UI Variable', 'system-ui', 'sans-serif'],
                display: ['var(--font-display)', 'Segoe UI', 'Segoe UI Variable', 'system-ui', 'sans-serif'],
                mono: ['var(--font-mono)', 'Cascadia Mono', 'Cascadia Code', 'Consolas', 'Courier New', 'ui-monospace', 'monospace'],
            },
            fontSize: {
                micro: ['var(--text-8)', { lineHeight: '1.2' }], 
                10: ['var(--text-10)', { lineHeight: '1.2' }],
                xxxs: ['var(--text-xxxs)', { lineHeight: '1.2' }],
                xxs: ['var(--text-xxs)', { lineHeight: '1.2' }],
                xs: ['var(--text-xs)', { lineHeight: '1.35' }],
                sm: ['var(--text-sm)', { lineHeight: '1.55' }],
                base: ['var(--text-base)', { lineHeight: '1.68' }],
                lg: ['var(--text-lg)', { lineHeight: '1.68' }],
                xl: ['var(--text-xl)', { lineHeight: '1.35' }],
                '2xl': ['var(--text-2xl)', { lineHeight: '1.35' }],
                '3xl': ['var(--text-3xl)', { lineHeight: '1.2' }],
                '4xl': ['var(--text-4xl)', { lineHeight: '1.2' }],
                '5xl': ['var(--text-5xl)', { lineHeight: '1.1' }],
            },
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                /* Semantic Colors */
                success: {
                    DEFAULT: 'hsl(var(--success))',
                    foreground: 'hsl(var(--success-foreground))',
                    light: 'hsl(var(--success-light))',
                },
                warning: {
                    DEFAULT: 'hsl(var(--warning))',
                    foreground: 'hsl(var(--warning-foreground))',
                    light: 'hsl(var(--warning-light))',
                },
                info: {
                    DEFAULT: 'hsl(var(--info))',
                    foreground: 'hsl(var(--info-foreground))',
                    light: 'hsl(var(--info-light))',
                },
                error: {
                    DEFAULT: 'hsl(var(--error))',
                    foreground: 'hsl(var(--error-foreground))',
                },
                neutral: {
                    DEFAULT: 'hsl(var(--neutral))',
                    light: 'hsl(var(--neutral-light))',
                    dark: 'hsl(var(--neutral-dark))',
                },
                indigo: 'hsl(var(--indigo))',
                purple: 'hsl(var(--purple))',
                cyan: 'hsl(var(--cyan))',
                orange: 'hsl(var(--orange))',
                fuchsia: 'hsl(var(--fuchsia))',
                /* Brand/Icon Colors */
                brand: {
                    typescript: 'var(--brand-typescript)',
                    javascript: 'var(--brand-javascript)',
                    react: 'var(--brand-react)',
                    python: 'var(--brand-python)',
                    rust: 'var(--brand-rust)',
                    database: 'var(--brand-database)',
                    go: 'var(--brand-go)',
                    ruby: 'var(--brand-ruby)',
                    php: 'var(--brand-php)',
                    java: 'var(--brand-java)',
                    swift: 'var(--brand-swift)',
                    c: 'var(--brand-c)',
                    cpp: 'var(--brand-cpp)',
                    csharp: 'var(--brand-csharp)',
                    git: 'var(--brand-git)',
                    flutter: 'var(--brand-flutter)',
                    html: 'var(--brand-html)',
                    css: 'var(--brand-css)',
                    sass: 'var(--brand-sass)',
                    vue: 'var(--brand-vue)',
                    svelte: 'var(--brand-svelte)',
                    angular: 'var(--brand-angular)',
                    docker: 'var(--brand-docker)',
                    kubernetes: 'var(--brand-kubernetes)',
                    nodejs: 'var(--nodejs)',
                },
                terminal: {
                    bg: 'var(--terminal-bg)',
                },
                git: {
                    modified: 'var(--git-modified)',
                    added: 'var(--git-added)',
                    deleted: 'var(--git-deleted)',
                    untracked: 'var(--git-untracked)',
                    ignored: 'var(--git-ignored)',
                    renamed: 'hsl(var(--primary))',
                    diff: {
                        added: {
                            text: 'var(--git-diff-added-text)',
                            bg: 'var(--git-diff-added-bg)',
                            border: 'var(--git-diff-added-border)',
                        },
                        deleted: {
                            text: 'var(--git-diff-deleted-text)',
                            bg: 'var(--git-diff-deleted-bg)',
                            border: 'var(--git-diff-deleted-border)',
                        },
                        neutral: {
                            text: 'var(--git-diff-neutral-text)',
                            bg: 'var(--git-diff-neutral-bg)',
                        },
                    },
                    gh: {
                        bg: 'var(--git-gh-bg)',
                        header: 'var(--git-gh-header)',
                        hover: 'var(--git-gh-hover)',
                    },
                    vsc: {
                        selected: 'var(--git-vsc-selected)',
                        hover: 'var(--git-vsc-hover)',
                        dim: 'var(--git-vsc-dim)',
                    },
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                DEFAULT: 'var(--tengra-radius-default)',
                none: 'var(--tengra-radius-none)',
                sm: 'var(--tengra-radius-sm)',
                md: 'var(--tengra-radius-md)',
                xl: 'var(--tengra-radius-xl)',
                '2xl': 'var(--tengra-radius-2xl)',
                '3xl': 'var(--tengra-radius-3xl)',
                full: 'var(--tengra-radius-full)',
                '1px': 'var(--tengra-radius-1px)',
                '2px': 'var(--tengra-radius-2px)',
                '3px': 'var(--tengra-radius-3px)',
                'inner-xl': 'var(--tengra-radius-inner-xl)',
                '6px': 'var(--tengra-radius-6px)',
                card: 'var(--tengra-radius-card)',
                'card-lg': 'var(--tengra-radius-card-lg)',
                'card-xl': 'var(--tengra-radius-card-xl)',
                'card-2xl': 'var(--tengra-radius-card-2xl)',
            },
            letterSpacing: {
                ...defaultTheme.letterSpacing,
                tighter: 'var(--tengra-tracking-tighter)',
                tight: 'var(--tengra-tracking-tight)',
                normal: 'var(--tengra-tracking-normal)',
                wide: 'var(--tengra-tracking-wide)',
                wider: 'var(--tengra-tracking-wider)',
                widest: 'var(--tengra-tracking-widest)',
                16: 'var(--tengra-tracking-16)',
                18: 'var(--tengra-tracking-18)',
                20: 'var(--tengra-tracking-20)',
                24: 'var(--tengra-tracking-24)',
                25: 'var(--tengra-tracking-25)',
                40: 'var(--tengra-tracking-40)',
                50: 'var(--tengra-tracking-50)',
                100: 'var(--tengra-tracking-100)',
                200: 'var(--tengra-tracking-200)',
                300: 'var(--tengra-tracking-300)',
                400: 'var(--tengra-tracking-400)',
                'ultra-wide': 'var(--tengra-tracking-ultra-wide)',
                'super-wide': 'var(--tengra-tracking-super-wide)',
                'mega-wide': 'var(--tengra-tracking-mega-wide)',
            },
            lineHeight: {
                ...defaultTheme.lineHeight,
                3: 'var(--tengra-leading-3)',
                4: 'var(--tengra-leading-4)',
                5: 'var(--tengra-leading-5)',
                6: 'var(--tengra-leading-6)',
                7: 'var(--tengra-leading-7)',
                8: 'var(--tengra-leading-8)',
                9: 'var(--tengra-leading-9)',
                10: 'var(--tengra-leading-10)',
                none: 'var(--tengra-leading-none)',
                tight: 'var(--tengra-leading-tight)',
                snug: 'var(--tengra-leading-snug)',
                normal: 'var(--tengra-leading-normal)',
                relaxed: 'var(--tengra-leading-relaxed)',
                loose: 'var(--tengra-leading-loose)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
                'progress-stripes': {
                    '0%': { backgroundPosition: '1rem 0' },
                    '100%': { backgroundPosition: '0 0' },
                },
                'confetti-fall': {
                    '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
                    '25%': { transform: 'translateY(25vh) rotate(180deg) translateX(20px)' },
                    '50%': { transform: 'translateY(50vh) rotate(360deg) translateX(-10px)' },
                    '75%': { transform: 'translateY(75vh) rotate(540deg) translateX(15px)', opacity: '0.8' },
                    '100%': { transform: 'translateY(100vh) rotate(720deg) translateX(-5px)', opacity: '0' },
                },
                'skeleton-shimmer': {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(100%)' },
                },
                'scroll-bounce-subtle': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-4px)' },
                },
                'scroll-bounce-in': {
                    '0%': { transform: 'scale(0)', opacity: '0' },
                    '50%': { transform: 'scale(1.2)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'typing-bounce': {
                    '0%, 60%, 100%': { transform: 'translateY(0)', opacity: '0.6' },
                    '30%': { transform: 'translateY(-4px)', opacity: '1' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'progress-stripes': 'progress-stripes 1s linear infinite',
                'confetti-fall': 'confetti-fall var(--confetti-duration, 3s) linear forwards',
                'skeleton-shimmer': 'skeleton-shimmer 1.5s infinite',
                'scroll-bounce-subtle': 'scroll-bounce-subtle 1s ease-in-out infinite',
                'scroll-bounce-in': 'scroll-bounce-in 300ms ease-out',
                'typing-bounce': 'typing-bounce 1.4s ease-in-out infinite',
            },
            transitionTimingFunction: {
                smooth: 'cubic-bezier(0.2, 0, 0, 1)',
            },
            transitionProperty: {
                width: 'width',
                margin: 'margin',
            },
            scale: {
                98: 'var(--tengra-scale-98)',
                101: 'var(--tengra-scale-101)',
                102: 'var(--tengra-scale-102)',
            },
            spacing: {
                // Override Tailwind default spacing scale to make layout fully themeable.
                0: 'var(--tengra-space-0)',
                px: 'var(--tengra-space-px)',
                '0.5': 'var(--tengra-space-0-5)',
                '1': 'var(--tengra-space-1)',
                '1.5': 'var(--tengra-space-1-5)',
                '2': 'var(--tengra-space-2)',
                '2.5': 'var(--tengra-space-2-5)',
                '3': 'var(--tengra-space-3)',
                '3.5': 'var(--tengra-space-3-5)',
                '4': 'var(--tengra-space-4)',
                '5': 'var(--tengra-space-5)',
                '6': 'var(--tengra-space-6)',
                '7': 'var(--tengra-space-7)',
                '8': 'var(--tengra-space-8)',
                '9': 'var(--tengra-space-9)',
                '10': 'var(--tengra-space-10)',
                '11': 'var(--tengra-space-11)',
                '12': 'var(--tengra-space-12)',
                '14': 'var(--tengra-space-14)',
                '16': 'var(--tengra-space-16)',
                '20': 'var(--tengra-space-20)',
                '24': 'var(--tengra-space-24)',
                '28': 'var(--tengra-space-28)',
                '32': 'var(--tengra-space-32)',
                '36': 'var(--tengra-space-36)',
                '40': 'var(--tengra-space-40)',
                '44': 'var(--tengra-space-44)',
                '48': 'var(--tengra-space-48)',
                '52': 'var(--tengra-space-52)',
                '56': 'var(--tengra-space-56)',
                '60': 'var(--tengra-space-60)',
                '64': 'var(--tengra-space-64)',
                '72': 'var(--tengra-space-72)',
                '80': 'var(--tengra-space-80)',
                '96': 'var(--tengra-space-96)',
                '1px': 'var(--tengra-space-1px)',
                '3px': 'var(--tengra-space-3px)',
                '5px': 'var(--tengra-space-5px)',
                70: 'var(--tengra-space-70)',
                84: 'var(--tengra-space-84)',
                90: 'var(--tengra-space-90)',
                sidebar: 'var(--sidebar-width)',
                terminal: 'var(--terminal-height)',
                100: 'var(--tengra-space-100)',
                120: 'var(--tengra-space-120)',
                140: 'var(--tengra-space-140)',
                148: 'var(--tengra-space-148)',
                160: 'var(--tengra-space-160)',
                172: 'var(--tengra-space-172)',
                180: 'var(--tengra-space-180)',
                200: 'var(--tengra-space-200)',
                220: 'var(--tengra-space-220)',
                240: 'var(--tengra-space-240)',
                250: 'var(--tengra-space-250)',
                260: 'var(--tengra-space-260)',
                280: 'var(--tengra-space-280)',
                300: 'var(--tengra-space-300)',
                320: 'var(--tengra-space-320)',
                340: 'var(--tengra-space-340)',
                350: 'var(--tengra-space-350)',
                360: 'var(--tengra-space-360)',
                380: 'var(--tengra-space-380)',
                400: 'var(--tengra-space-400)',
                420: 'var(--tengra-space-420)',
                440: 'var(--tengra-space-440)',
                460: 'var(--tengra-space-460)',
                480: 'var(--tengra-space-480)',
                500: 'var(--tengra-space-500)',
                520: 'var(--tengra-space-520)',
                '1-25rem': 'var(--tengra-space-1-25rem)',
            },
            zIndex: {
                ...defaultTheme.zIndex,
                0: 'var(--tengra-z-0)',
                1: 'var(--tengra-z-1)',
                10: 'var(--tengra-z-10)',
                20: 'var(--tengra-z-20)',
                30: 'var(--tengra-z-30)',
                40: 'var(--tengra-z-40)',
                50: 'var(--tengra-z-50)',
                95: 'var(--tengra-z-95)',
                100: 'var(--tengra-z-100)',
                1000: 'var(--tengra-z-1000)',
                150: 'var(--tengra-z-150)',
                9999: 'var(--tengra-z-9999)',
                99999: 'var(--tengra-z-99999)',
                10001: 'var(--tengra-z-10001)',
                10002: 'var(--tengra-z-10002)',
            },
            translate: {
                ...defaultTheme.translate,
                '1px': 'var(--tengra-translate-1px)',
            },
            width: {
                110: 'var(--tengra-w-110)',
                450: 'var(--tengra-w-450)',
                '46p': 'var(--tengra-w-46p)',
                '70p': 'var(--tengra-w-70p)',
                'modal-72': 'var(--tengra-w-modal-72)',
                'modal-32': 'var(--tengra-w-modal-32)',
                'command-menu': 'var(--tengra-w-command-menu)',
            },
            minWidth: {
                60: 'var(--tengra-minw-60)',
                16: 'var(--tengra-minw-16)',
                36: 'var(--tengra-minw-36)',
                48: 'var(--tengra-minw-48)',
                140: 'var(--tengra-minw-140)',
                200: 'var(--tengra-minw-200)',
                420: 'var(--tengra-minw-420)',
                'radix-select-trigger': 'var(--radix-select-trigger-width)',
            },
            minHeight: {
                300: 'var(--tengra-minh-300)',
                400: 'var(--tengra-minh-400)',
                500: 'var(--tengra-minh-500)',
            },
            height: {
                '2px': 'var(--tengra-h-2px)',
                22: 'var(--tengra-h-22)',
                40: 'var(--tengra-h-40)',
                48: 'var(--tengra-h-48)',
                60: 'var(--tengra-h-60)',
                450: 'var(--tengra-h-450)',
                480: 'var(--tengra-h-480)',
                500: 'var(--tengra-h-500)',
                580: 'var(--tengra-h-580)',
                600: 'var(--tengra-h-600)',
                '60vh': 'var(--tengra-h-60vh)',
                'dialog-ssh': 'var(--tengra-h-dialog-ssh)',
                'screen-minus-200': 'var(--tengra-h-screen-minus-200)',
                'radix-select-trigger': 'var(--radix-select-trigger-height)',
            },
            maxHeight: {
                '85vh': 'var(--tengra-maxh-85vh)',
                '88vh': 'var(--tengra-maxh-88vh)',
                '90vh': 'var(--tengra-maxh-90vh)',
                dialog: 'var(--tengra-maxh-dialog)',
                'screen-minus-32': 'var(--tengra-maxh-screen-minus-32)',
            },
            maxWidth: {
                ...defaultTheme.maxWidth,
                112: 'var(--tengra-maxw-112)',
                '90p': 'var(--tengra-maxw-90p)',
                '95p': 'var(--tengra-maxw-95p)',
                '95vw': 'var(--tengra-maxw-95vw)',
                xxs: 'var(--tengra-maxw-xxs)',
                xs: 'var(--tengra-maxw-xs)',
                '2xs': 'var(--tengra-maxw-2xs)',
                '3xs': 'var(--tengra-maxw-3xs)',
                sm: 'var(--tengra-maxw-sm)',
                md: 'var(--tengra-maxw-md)',
                lg: 'var(--tengra-maxw-lg)',
                xl: 'var(--tengra-maxw-xl)',
                '2xl': 'var(--tengra-maxw-2xl)',
                '3xl': 'var(--tengra-maxw-3xl)',
                '4xl': 'var(--tengra-maxw-4xl)',
                '5xl': 'var(--tengra-maxw-5xl)',
                '6xl': 'var(--tengra-maxw-6xl)',
                '7xl': 'var(--tengra-maxw-7xl)',
                120: 'var(--tengra-maxw-120)',
                220: 'var(--tengra-maxw-220)',
                240: 'var(--tengra-maxw-240)',
                400: 'var(--tengra-maxw-400)',
                820: 'var(--tengra-maxw-820)',
                container: 'var(--tengra-maxw-container)',
                'container-sm': 'var(--tengra-maxw-container-sm)',
                'container-md': 'var(--tengra-maxw-container-md)',
                'container-lg': 'var(--tengra-maxw-container-lg)',
                'container-xl': 'var(--tengra-maxw-container-xl)',
                'screen-sm': 'var(--tengra-maxw-screen-sm)',
                'screen-md': 'var(--tengra-maxw-screen-md)',
                'screen-lg': 'var(--tengra-maxw-screen-lg)',
                'screen-xl': 'var(--tengra-maxw-screen-xl)',
                'screen-2xl': 'var(--tengra-maxw-screen-2xl)',
                200: 'var(--tengra-maxw-200)',
                420: 'var(--tengra-maxw-420)',
            },
            inset: {
                'full-plus-2': 'var(--tengra-inset-full-plus-2)',
                '38px': 'var(--left-38px)',
                '36px': 'var(--top-36px)',
            },
            gridTemplateColumns: {
                todo: 'var(--tengra-grid-cols-todo)',
                '380-main': 'var(--tengra-grid-cols-380-main)',
                '2fr-1fr': 'var(--tengra-grid-cols-2fr-1fr)',
                '80-main': 'var(--tengra-grid-cols-80-main)',
                'balance-95-105': 'var(--tengra-grid-cols-balance-95-105)',
                '360-main': 'var(--tengra-grid-cols-360-main)',
                'editor-split': 'var(--tengra-grid-cols-editor-split)',
            },
            gridAutoRows: {
                260: 'var(--tengra-grid-rows-260)',
            },
            flex: {
                2: 'var(--tengra-flex-2)',
            },
            borderWidth: {
                ...defaultTheme.borderWidth,
                DEFAULT: 'var(--tengra-border-1)',
                0: 'var(--tengra-border-0)',
                2: 'var(--tengra-border-2)',
                4: 'var(--tengra-border-4)',
                6: 'var(--tengra-border-6)',
                8: 'var(--tengra-border-8)',
            },
            ringWidth: {
                ...defaultTheme.ringWidth,
                DEFAULT: 'var(--tengra-ring-1)',
                0: 'var(--tengra-ring-0)',
                1: 'var(--tengra-ring-1)',
                2: 'var(--tengra-ring-2)',
                4: 'var(--tengra-ring-4)',
                8: 'var(--tengra-ring-8)',
            },
            ringOffsetWidth: {
                ...defaultTheme.ringOffsetWidth,
                0: 'var(--tengra-ring-offset-0)',
                1: 'var(--tengra-ring-offset-1)',
                2: 'var(--tengra-ring-offset-2)',
                4: 'var(--tengra-ring-offset-4)',
                8: 'var(--tengra-ring-offset-8)',
            },
            outlineOffset: {
                0: 'var(--tengra-outline-offset-0)',
                1: 'var(--tengra-outline-offset-1)',
                2: 'var(--tengra-outline-offset-2)',
                4: 'var(--tengra-outline-offset-4)',
                8: 'var(--tengra-outline-offset-8)',
            },
            strokeWidth: {
                3: '3',
                2.5: 'var(--stroke-2-5)',
            },
            blur: {
                ...defaultTheme.blur,
                sm: 'var(--tengra-blur-sm)',
                DEFAULT: 'var(--tengra-blur-default)',
                md: 'var(--tengra-blur-md)',
                lg: 'var(--tengra-blur-lg)',
                xl: 'var(--tengra-blur-xl)',
                '2xl': 'var(--tengra-blur-2xl)',
                '3xl': 'var(--tengra-blur-3xl)',
                1: 'var(--blur-1px)',
            },
            backdropBlur: {
                ...defaultTheme.backdropBlur,
                sm: 'var(--tengra-backdrop-blur-sm)',
                DEFAULT: 'var(--tengra-backdrop-blur-default)',
                md: 'var(--tengra-backdrop-blur-md)',
                lg: 'var(--tengra-backdrop-blur-lg)',
                xl: 'var(--tengra-backdrop-blur-xl)',
                '2xl': 'var(--tengra-backdrop-blur-2xl)',
                '3xl': 'var(--tengra-backdrop-blur-3xl)',
                2: 'var(--tengra-backdrop-blur-2)',
                4: 'var(--tengra-backdrop-blur-4)',
                8: 'var(--tengra-backdrop-blur-8)',
                16: 'var(--tengra-backdrop-blur-16)',
            },
            opacity: {
                ...defaultTheme.opacity,
                0: 'var(--tengra-opacity-0)',
                5: 'var(--tengra-opacity-5)',
                10: 'var(--tengra-opacity-10)',
                15: 'var(--tengra-opacity-15)',
                20: 'var(--tengra-opacity-20)',
                25: 'var(--tengra-opacity-25)',
                30: 'var(--tengra-opacity-30)',
                35: 'var(--tengra-opacity-35)',
                40: 'var(--tengra-opacity-40)',
                45: 'var(--tengra-opacity-45)',
                50: 'var(--tengra-opacity-50)',
                55: 'var(--tengra-opacity-55)',
                60: 'var(--tengra-opacity-60)',
                65: 'var(--tengra-opacity-65)',
                70: 'var(--tengra-opacity-70)',
                75: 'var(--tengra-opacity-75)',
                80: 'var(--tengra-opacity-80)',
                85: 'var(--tengra-opacity-85)',
                90: 'var(--tengra-opacity-90)',
                95: 'var(--tengra-opacity-95)',
                100: 'var(--tengra-opacity-100)',
                '03': 'var(--opacity-03)',
                '02': 'var(--opacity-02)',
                '04': 'var(--opacity-04)',
            },
            willChange: {
                opacity: 'opacity',
            },
            backgroundImage: {
                'progress-stripes-white': 'var(--progress-stripes-white)',
                'skeleton-shimmer':
                    'linear-gradient(90deg,transparent 0%,hsl(var(--muted-foreground)/0.1) 50%,transparent 100%)',
                checker:
                    'linear-gradient(45deg, hsl(var(--muted)) 25%, transparent 25%), linear-gradient(-45deg, hsl(var(--muted)) 25%, transparent 25%), linear-gradient(45deg, transparent 75%, hsl(var(--muted)) 75%), linear-gradient(-45deg, transparent 75%, hsl(var(--muted)) 75%)',
            },
            boxShadow: {
                ...defaultTheme.boxShadow,
                sm: 'var(--tengra-shadow-sm)',
                DEFAULT: 'var(--tengra-shadow)',
                md: 'var(--tengra-shadow-md)',
                lg: 'var(--tengra-shadow-lg)',
                xl: 'var(--tengra-shadow-xl)',
                '2xl': 'var(--tengra-shadow-2xl)',
                inner: 'var(--tengra-shadow-inner)',
                'premium-sm': 'var(--shadow-sm)',
                'premium-md': 'var(--shadow-md)',
                'premium-lg': 'var(--shadow-lg)',
                'premium-primary': '0 0 15px hsl(var(--primary) / 0.1)',
                'premium-success': '0 0 15px hsl(var(--success) / 0.1)',
                'premium-destructive': '0 0 15px hsl(var(--destructive) / 0.1)',
                'card-sm': 'var(--shadow-card-sm)',
                'card-md': 'var(--shadow-card-md)',
                'card-dark': 'var(--shadow-card-dark)',
                'glow-amber': 'var(--shadow-glow-amber)',
                'glow-success': 'var(--shadow-glow-success)',
                'glow-success-strong': 'var(--shadow-glow-success-strong)',
                'modal-heavy': 'var(--shadow-modal-heavy)',
                elevated: 'var(--tengra-shadow-elevated)',
                'primary-elevated': 'var(--tengra-shadow-primary-elevated)',
                'primary-medium': 'var(--tengra-shadow-primary-medium)',
                'primary-outline': 'var(--tengra-shadow-primary-outline)',
                'primary-glow': 'var(--tengra-shadow-primary-glow)',
                'purple-soft': 'var(--tengra-shadow-purple-soft)',
                'outline-background-2': 'var(--tengra-shadow-outline-background-2)',
                'outline-primary-1': 'var(--tengra-shadow-outline-primary-1)',
                'glow-primary-strong': 'var(--tengra-shadow-glow-primary-strong)',
                'glow-primary-soft': 'var(--tengra-shadow-glow-primary-soft)',
                'glow-primary-rgb': 'var(--tengra-shadow-glow-primary-rgb)',
                'glow-primary': 'var(--tengra-shadow-glow-primary)',
                'glow-primary-subtle': 'var(--tengra-shadow-glow-primary-subtle)',
                'glow-primary-rgb-soft': 'var(--tengra-shadow-glow-primary-rgb-soft)',
                'glow-destructive': 'var(--tengra-shadow-glow-destructive)',
                'glow-destructive-rgb': 'var(--tengra-shadow-glow-destructive-rgb)',
                'glow-warning': 'var(--tengra-shadow-glow-warning)',
                'glow-primary-ring': 'var(--tengra-shadow-glow-primary-ring)',
                'edge-primary': 'var(--tengra-shadow-edge-primary)',
                'glow-primary-lg': 'var(--tengra-shadow-glow-primary-lg)',
                'glow-primary-hsl': 'var(--tengra-shadow-glow-primary-hsl)',
                'glow-primary-file': 'var(--tengra-shadow-glow-primary-file)',
                'modal-foreground': 'var(--tengra-shadow-modal-foreground)',
            },
            dropShadow: {
                ...defaultTheme.dropShadow,
                sm: 'var(--tengra-drop-shadow-sm)',
                DEFAULT: 'var(--tengra-drop-shadow)',
                md: 'var(--tengra-drop-shadow-md)',
                lg: 'var(--tengra-drop-shadow-lg)',
                xl: 'var(--tengra-drop-shadow-xl)',
                '2xl': 'var(--tengra-drop-shadow-2xl)',
            },
        },
    },
    plugins: [
        require('tailwindcss-animate'),
        plugin(({ addUtilities }) => {
            addUtilities({
                '.animate-delay-150': { 'animation-delay': '-0.15s' },
                '.animate-delay-300': { 'animation-delay': '-0.3s' },
                '.transform-3d': { 'transform-style': 'preserve-3d' },
                '.bg-size-progress': { 'background-size': '1rem 1rem' },
            });
        }),
    ],
};
