const plugin = require('tailwindcss/plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class'],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
    ],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
                '3xl': '1800px',
            },
        },
        extend: {
            fontFamily: {
                sans: ['var(--font-sans)', 'Segoe UI', 'Segoe UI Variable', 'system-ui', 'sans-serif'],
                display: ['var(--font-display)', 'Segoe UI', 'Segoe UI Variable', 'system-ui', 'sans-serif'],
                mono: ['var(--font-mono)', 'Cascadia Mono', 'Cascadia Code', 'Consolas', 'Courier New', 'ui-monospace', 'monospace'],
            },
            fontSize: {
                micro: ['0.5rem', { lineHeight: '1.2' }],
                8: ['0.5rem', { lineHeight: '1.2' }],
                9: ['0.5625rem', { lineHeight: '1.2' }],
                10: ['0.625rem', { lineHeight: '1.2' }],
                11: ['0.6875rem', { lineHeight: '1.2' }],
                12: ['0.75rem', { lineHeight: '1.3' }],
                13: ['0.8125rem', { lineHeight: '1.4' }],
                14: ['0.875rem', { lineHeight: '1.55' }],
                xxxs: ['0.625rem', { lineHeight: '1.2' }],
                xxs: ['0.6875rem', { lineHeight: '1.2' }],
                xs: ['0.8125rem', { lineHeight: '1.35' }],
                sm: ['0.875rem', { lineHeight: '1.55' }],
                base: ['1rem', { lineHeight: '1.68' }],
                lg: ['1.0625rem', { lineHeight: '1.68' }],
                xl: ['1.25rem', { lineHeight: '1.35' }],
                '2xl': ['1.5rem', { lineHeight: '1.35' }],
                '3xl': ['1.875rem', { lineHeight: '1.2' }],
                '4xl': ['2.25rem', { lineHeight: '1.2' }],
                '5xl': ['2.75rem', { lineHeight: '1.1' }],
            },
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                /* Semantic Colors */
                success: {
                    DEFAULT: 'hsl(var(--success))',
                    foreground: 'hsl(var(--success-foreground))',
                    light: 'hsl(var(--success-light))',
                },
                warning: {
                    DEFAULT: 'hsl(var(--warning))',
                    foreground: 'hsl(var(--warning-foreground))',
                    light: 'hsl(var(--warning-light))',
                },
                info: {
                    DEFAULT: 'hsl(var(--info))',
                    foreground: 'hsl(var(--info-foreground))',
                    light: 'hsl(var(--info-light))',
                },
                error: {
                    DEFAULT: 'hsl(var(--error))',
                    foreground: 'hsl(var(--error-foreground))',
                },
                neutral: {
                    DEFAULT: 'hsl(var(--neutral))',
                    light: 'hsl(var(--neutral-light))',
                    dark: 'hsl(var(--neutral-dark))',
                },
                indigo: 'hsl(var(--indigo))',
                purple: 'hsl(var(--purple))',
                cyan: 'hsl(var(--cyan))',
                orange: 'hsl(var(--orange))',
                fuchsia: 'hsl(var(--fuchsia))',
                /* Brand/Icon Colors */
                brand: {
                    typescript: '#3178C6',
                    javascript: '#F7DF1E',
                    react: '#61DAFB',
                    python: '#3776AB',
                    rust: '#F37626',
                    database: '#DEA584',
                    go: '#00ADD8',
                    ruby: '#CC342D',
                    php: '#777BB4',
                    java: '#ED8B00',
                    swift: '#7F52FF',
                    c: '#A8B9CC',
                    cpp: '#00599C',
                    csharp: '#512BD4',
                    git: '#F05138',
                    flutter: '#0175C2',
                    html: '#E34F26',
                    css: '#1572B6',
                    sass: '#CF649A',
                    vue: '#42B883',
                    svelte: '#FF3E00',
                    angular: '#DD0031',
                    docker: '#2496ED',
                    kubernetes: '#326CE5',
                    nodejs: '#339933',
                },
                git: {
                    modified: '#e2c522',
                    added: '#81b88b',
                    deleted: '#c74e39',
                    untracked: '#73c991',
                    ignored: '#8e8e8e',
                    renamed: 'hsl(var(--primary))',
                    diff: {
                        added: {
                            text: '#3fb950',
                            bg: '#2ea04326',
                            border: '#3fb950',
                        },
                        deleted: {
                            text: '#f85149',
                            bg: '#f851491a',
                            border: '#f85149',
                        },
                        neutral: {
                            text: '#7d8590',
                            bg: '#161b22',
                        },
                    },
                    gh: {
                        bg: '#0d1117',
                        header: '#161b22',
                        hover: '#1c2128',
                    },
                    vsc: {
                        selected: '#37373d',
                        hover: '#2a2d2e',
                        dim: '#cccccc',
                    },
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
                '1px': '1px',
                '2px': '2px',
                '3px': '3px',
                'inner-xl': 'calc(0.75rem - 2px)',
                '6px': '6px',
                'card': '1.5rem',
                'card-lg': '2rem',
                'card-xl': '2.5rem',
                'card-2xl': '1.75rem',
            },
            letterSpacing: {
                16: '0.016em',
                18: '0.018em',
                20: '0.02em',
                24: '0.024em',
                25: '0.025em',
                40: '0.04em',
                50: '0.05em',
                100: '0.1em',
                200: '0.2em',
                300: '0.3em',
                400: '0.4em',
                'ultra-wide': '0.15em',
                'super-wide': '0.2em',
                'mega-wide': '0.3em',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
                'progress-stripes': {
                    '0%': { backgroundPosition: '1rem 0' },
                    '100%': { backgroundPosition: '0 0' },
                },
                'confetti-fall': {
                    '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '1' },
                    '25%': { transform: 'translateY(25vh) rotate(180deg) translateX(20px)' },
                    '50%': { transform: 'translateY(50vh) rotate(360deg) translateX(-10px)' },
                    '75%': { transform: 'translateY(75vh) rotate(540deg) translateX(15px)', opacity: '0.8' },
                    '100%': { transform: 'translateY(100vh) rotate(720deg) translateX(-5px)', opacity: '0' },
                },
                'skeleton-shimmer': {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(100%)' },
                },
                'scroll-bounce-subtle': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-4px)' },
                },
                'scroll-bounce-in': {
                    '0%': { transform: 'scale(0)', opacity: '0' },
                    '50%': { transform: 'scale(1.2)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'typing-bounce': {
                    '0%, 60%, 100%': { transform: 'translateY(0)', opacity: '0.6' },
                    '30%': { transform: 'translateY(-4px)', opacity: '1' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'progress-stripes': 'progress-stripes 1s linear infinite',
                'confetti-fall': 'confetti-fall var(--confetti-duration, 3s) linear forwards',
                'skeleton-shimmer': 'skeleton-shimmer 1.5s infinite',
                'scroll-bounce-subtle': 'scroll-bounce-subtle 1s ease-in-out infinite',
                'scroll-bounce-in': 'scroll-bounce-in 300ms ease-out',
                'typing-bounce': 'typing-bounce 1.4s ease-in-out infinite',
            },
            transitionTimingFunction: {
                smooth: 'cubic-bezier(0.2, 0, 0, 1)',
            },
            transitionProperty: {
                width: 'width',
            },
            scale: {
                98: '0.98',
                101: '1.01',
                102: '1.02',
            },
            spacing: {
                '1px': '1px',
                '3px': '3px',
                '5px': '5px',
                70: '70px',
                84: '84px',
                90: '90px',
                sidebar: 'var(--sidebar-width)',
                terminal: 'var(--terminal-height)',
                100: '100px',
                120: '120px',
                140: '140px',
                148: '148px',
                160: '160px',
                172: '172px',
                180: '180px',
                200: '200px',
                220: '220px',
                240: '240px',
                250: '250px',
                260: '260px',
                280: '280px',
                300: '300px',
                320: '320px',
                340: '340px',
                350: '350px',
                360: '360px',
                380: '380px',
                400: '400px',
                420: '420px',
                440: '440px',
                460: '460px',
                480: '480px',
                500: '500px',
                520: '520px',
            },
            zIndex: {
                ...defaultTheme.zIndex,
                95: '95',
                100: '100',
                150: '150',
                10001: '10001',
                10002: '10002',
            },
            width: {
                110: '110px',
                450: '450px',
                '46p': '46%',
                '70p': '70%',
                'modal-72': 'min(100%, 72rem)',
                'modal-32': 'min(100%, 32rem)',
                'command-menu': 'min(20rem, calc(100vw - 2rem))',
            },
            minWidth: {
                16: '16px',
                36: '36px',
                48: '48px',
                140: '140px',
                200: '200px',
                420: '420px',
                'radix-select-trigger': 'var(--radix-select-trigger-width)',
            },
            minHeight: {
                500: '500px',
                400: '400px',
            },
            height: {
                '2px': '2px',
                22: '22px',
                40: '40px',
                48: '48px',
                60: '60px',
                450: '450px',
                480: '480px',
                580: '580px',
                600: '600px',
                '60vh': '60vh',
                'dialog-ssh': 'min(88vh, 42rem)',
                'screen-minus-200': 'calc(100vh - 200px)',
                'radix-select-trigger': 'var(--radix-select-trigger-height)',
            },
            maxHeight: {
                '85vh': '85vh',
                '88vh': '88vh',
                'dialog': 'min(88vh, 44rem)',
                'screen-minus-32': 'calc(100vh - 8rem)',
            },
            maxWidth: {
                112: '28rem',
                '90p': '90%',
                '95vw': '95vw',
                xxs: '12rem',
                '2xs': '16rem',
                '3xs': '14rem',
                120: '120px',
                220: '220px',
                240: '240px',
                400: '400px',
                820: '820px',
                'container-sm': '640px',
                'container-md': '768px',
                'container-lg': '1024px',
                'container-xl': '1280px',
            },
            inset: {
                'full-plus-2': 'calc(100% + 0.5rem)',
            },
            gridTemplateColumns: {
                todo: '2rem minmax(0,1.2fr) minmax(0,1.3fr) minmax(0,0.9fr) auto',
                '380-main': '380px minmax(0,1fr)',
                '2fr-1fr': '2fr 1fr',
                '80-main': '20rem minmax(0,1fr)',
                'balance-95-105': 'minmax(0,0.95fr) minmax(0,1.05fr)',
                '360-main': '360px minmax(0,1fr)',
            },
            gridAutoRows: {
                260: '260px',
            },
            flex: {
                2: '2 2 0%',
            },
            borderWidth: {
                6: '6px',
            },
            zIndex: {
                100: '100',
                9999: '9999',
                99999: '99999',
            },
            strokeWidth: {
                3: '3',
            },
            backdropBlur: {
                2: '2px',
                4: '4px',
                8: '8px',
                16: '16px',
            },
            opacity: {
                ...defaultTheme.opacity,
                '03': '0.03',
            },
            willChange: {
                opacity: 'opacity',
            },
            backgroundImage: {
                'progress-stripes-white':
                    'linear-gradient(45deg,rgba(255,255,255,0.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,0.15) 50%,rgba(255,255,255,0.15) 75%,transparent 75%,transparent)',
                'skeleton-shimmer':
                    'linear-gradient(90deg,transparent 0%,hsl(var(--muted-foreground)/0.1) 50%,transparent 100%)',
                checker:
                    'linear-gradient(45deg, hsl(var(--muted)) 25%, transparent 25%), linear-gradient(-45deg, hsl(var(--muted)) 25%, transparent 25%), linear-gradient(45deg, transparent 75%, hsl(var(--muted)) 75%), linear-gradient(-45deg, transparent 75%, hsl(var(--muted)) 75%)',
            },
            boxShadow: {
                'premium-sm': 'var(--shadow-sm)',
                'premium-md': 'var(--shadow-md)',
                'premium-lg': 'var(--shadow-lg)',
                'premium-primary': '0 0 15px hsl(var(--primary) / 0.1)',
                'premium-success': '0 0 15px hsl(var(--success) / 0.1)',
                'premium-destructive': '0 0 15px hsl(var(--destructive) / 0.1)',
                'card-sm': '0 2px 8px -2px rgba(0,0,0,0.1)',
                'card-md': '0 2px 8px -2px rgba(0,0,0,0.2)',
                'card-dark': '0 0 8px rgba(0,0,0,0.2)',
                'glow-amber': '0 0 8px rgba(245,158,11,0.15)',
                'glow-success': '0 0 8px rgba(34,197,94,0.4)',
                'glow-success-strong': '0 0 10px rgba(34,197,94,0.6)',
                'modal-heavy': '0 32px 64px -16px rgba(0,0,0,0.3)',
                elevated: '0 8px 24px -8px hsl(var(--shadow-color) / 0.25)',
                'primary-elevated': '0 10px 26px -10px hsl(var(--primary) / 0.35)',
                'primary-medium': '0 6px 16px -8px hsl(var(--primary) / 0.25)',
                'primary-outline': '0 0 0 1px hsl(var(--primary) / 0.45)',
                'primary-glow': '0 0 16px hsl(var(--primary) / 0.4)',
                'purple-soft': '0 0 12px hsl(var(--purple) / 0.35)',
                'outline-background-2': '0 0 0 2px hsl(var(--background))',
                'outline-primary-1': '0 0 0 1px hsl(var(--primary) / 0.5)',
                'glow-primary-strong': '0 0 10px hsl(var(--primary) / 0.5)',
                'glow-primary-soft': '0 0 10px hsl(var(--primary) / 0.2)',
                'glow-primary-rgb': '0 0 10px hsl(var(--primary) / 0.4)',
                'glow-primary': '0 0 8px hsl(var(--primary) / 0.5)',
                'glow-primary-subtle': '0 0 8px hsl(var(--primary) / 0.3)',
                'glow-primary-rgb-soft': '0 0 8px hsl(var(--primary) / 0.4)',
                'glow-destructive': '0 0 8px hsl(var(--destructive) / 0.6)',
                'glow-destructive-rgb': '0 0 8px hsl(var(--destructive) / 0.5)',
                'glow-warning': '0 0 8px hsl(var(--warning) / 0.4)',
                'glow-primary-ring': '0 0 15px hsl(var(--primary) / 0.1)',
                'edge-primary': '2px 0 8px hsl(var(--primary) / 0.5)',
                'glow-primary-lg': '0 0 20px hsl(var(--primary) / 0.2)',
                'glow-primary-hsl': '0 0 20px hsl(var(--primary) / 0.3)',
                'modal-foreground': '0 25px 50px -12px hsl(var(--foreground) / 0.25)',
            },
        },
    },
    plugins: [
        require('tailwindcss-animate'),
        plugin(({ addUtilities }) => {
            addUtilities({
                '.animate-delay-150': { 'animation-delay': '-0.15s' },
                '.animate-delay-300': { 'animation-delay': '-0.3s' },
                '.transform-3d': { 'transform-style': 'preserve-3d' },
                '.bg-size-progress': { 'background-size': '1rem 1rem' },
            });
        }),
    ],
};
