const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..', '..');
const SOURCE_FILE = path.join(ROOT_DIR, 'docs', 'changelog', 'data', 'changelog.entries.json');
const LOCALES_DIR = path.join(ROOT_DIR, 'docs', 'changelog', 'i18n');
const LOCALES_CONFIG_FILE = path.join(LOCALES_DIR, 'locales.json');
const LOCALE_TODO_FILE = path.join(ROOT_DIR, 'docs', 'changelog', 'i18n', 'LOCALE_TODO.md');

function readJson(filePath, fallback) {
    if (!fs.existsSync(filePath)) {
        return fallback;
    }
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, value) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function slugify(value) {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 80);
}

function parseArgs() {
    const args = process.argv.slice(2);
    const map = {};
    for (const arg of args) {
        if (!arg.startsWith('--') || !arg.includes('=')) {
            continue;
        }
        const [rawKey, ...rawValueParts] = arg.slice(2).split('=');
        map[rawKey] = rawValueParts.join('=').trim();
    }
    return map;
}

function requireArg(map, key) {
    const value = map[key];
    if (!value || value.length === 0) {
        throw new Error(`Missing required argument --${key}=...`);
    }
    return value;
}

function assertIsoDate(value) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
        throw new Error('Date must be YYYY-MM-DD.');
    }
}

function parseItems(rawItems) {
    return rawItems
        .split('|')
        .map((item) => item.trim())
        .filter((item) => item.length > 0)
        .map((item) => (item.startsWith('- ') ? item : `- ${item}`));
}

function updateLocaleTodo(id, overrideLocales) {
    const now = new Date().toISOString();
    const existing = fs.existsSync(LOCALE_TODO_FILE)
        ? fs.readFileSync(LOCALE_TODO_FILE, 'utf8')
        : '';

    const lines = existing.length > 0
        ? existing.split(/\r?\n/)
        : [
            '# Locale Translation TODO',
            '',
            'Generated by `scripts/changelog/new-entry.cjs`.',
            '',
            'Mark locale work done only after editorial review.',
            '',
        ];

    for (const localeCode of overrideLocales) {
        const marker = `- [ ] ${localeCode}: ${id}`;
        if (!lines.some((line) => line.includes(`${localeCode}: ${id}`))) {
            lines.push(`${marker} (title + summary + items)`);
        }
    }

    if (!lines.some((line) => line.startsWith('Last updated:'))) {
        lines.splice(1, 0, `Last updated: ${now}`, '');
    } else {
        for (let i = 0; i < lines.length; i += 1) {
            if (lines[i].startsWith('Last updated:')) {
                lines[i] = `Last updated: ${now}`;
                break;
            }
        }
    }

    fs.writeFileSync(LOCALE_TODO_FILE, `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`, 'utf8');
}

function run() {
    const args = parseArgs();
    const date = requireArg(args, 'date');
    const title = requireArg(args, 'title');
    const summary = requireArg(args, 'summary');
    const itemsArg = requireArg(args, 'items');

    assertIsoDate(date);
    const items = parseItems(itemsArg);
    if (items.length === 0) {
        throw new Error('At least one item is required.');
    }

    const source = readJson(SOURCE_FILE, null);
    if (!source || !Array.isArray(source.entries)) {
        throw new Error('Invalid changelog source file.');
    }

    const baseId = `${date}-${slugify(title)}`;
    const id = args.id && args.id.length > 0 ? args.id : baseId;
    if (source.entries.some((entry) => entry.id === id)) {
        throw new Error(`Entry id already exists: ${id}`);
    }

    const entry = {
        id,
        date,
        channel: args.channel || 'stable',
        type: args.type || 'feature',
        status: args.status || 'completed',
        audience: ['end-user', 'developer'],
        components: [],
        breaking: false,
        security: (args.type || 'feature') === 'security',
        translations: {
            en: {
                title,
                summary,
                items,
            },
        },
    };

    source.entries.push(entry);
    source.generatedFrom = 'docs/changelog/data/changelog.entries.json';
    source.generatedAt = new Date().toISOString();
    writeJson(SOURCE_FILE, source);

    const localeConfig = readJson(LOCALES_CONFIG_FILE, { locales: [] });
    const overrideLocales = (localeConfig.locales ?? [])
        .filter((locale) => locale.code !== 'en' && locale.validateOverrides !== false)
        .map((locale) => locale.code);

    for (const localeCode of overrideLocales) {
        const filePath = path.join(LOCALES_DIR, `${localeCode}.overrides.json`);
        const overrides = readJson(filePath, {});
        overrides[id] = {
            title,
            summary,
            items,
        };
        writeJson(filePath, overrides);
    }

    updateLocaleTodo(id, overrideLocales);

    console.log(`Added changelog entry: ${id}`);
}

run();
