import path from 'path'
import fs from 'fs'
import axios from 'axios'
import crypto from 'crypto'
import os from 'os'
import { app } from 'electron'
import { SettingsService } from './settings.service'

export class ProxyService {
  private configPath: string
  private settingsService: SettingsService

  constructor(settingsService: SettingsService) {
    this.settingsService = settingsService

    this.configPath = path.join(app.getPath('userData'), 'proxy-config.yaml')
    this.ensureAuthStoreKey()
    this.ensureProxyKey()
  }

  private ensureProxyKey(): string {
    const settings = this.settingsService.getSettings()
    const existing = settings.proxy?.key?.trim()
    if (existing) return existing

    const generated = crypto.randomBytes(32).toString('base64')
    this.settingsService.saveSettings({
      proxy: {
        ...(settings.proxy || {
          enabled: true,
          url: 'http://localhost:8317/v1',
          key: '',
          authStoreKey: ''
        }),
        key: generated
      }
    })
    return generated
  }

  getProxyKey(): string {
    const settings = this.settingsService.getSettings()
    return settings.proxy?.key?.trim() || this.ensureProxyKey()
  }

  private ensureAuthStoreKey(): string {
    const settings = this.settingsService.getSettings()
    const existing = settings.proxy?.authStoreKey?.trim()
    if (existing) return existing

    const generated = crypto.randomBytes(32).toString('base64')
    this.settingsService.saveSettings({
      proxy: {
        ...(settings.proxy || {
          enabled: true,
          url: 'http://localhost:8317/v1',
          key: 'local-dev-key',
          authStoreKey: ''
        }),
        authStoreKey: generated
      }
    })
    return generated
  }

  getAuthStoreKey(): string {
    const settings = this.settingsService.getSettings()
    return settings.proxy?.authStoreKey?.trim() || this.ensureAuthStoreKey()
  }

  getAuthStorePath(): string {
    return path.join(app.getPath('userData'), 'cliproxy-auth.enc')
  }

  getAuthWorkDir(): string {
    return path.join(app.getPath('userData'), 'cliproxy-auth-work')
  }

  prepareAuthWorkDir(): void {
    const authDir = this.getAuthWorkDir()
    if (!fs.existsSync(authDir)) {
      fs.mkdirSync(authDir, { recursive: true })
    }
    this.migrateLegacyAuthFiles(authDir)
  }

  private migrateLegacyAuthFiles(authDir: string): void {
    const hasJson = this.hasAuthJsonFiles(authDir)
    if (hasJson) {
      return
    }

    const legacyDirs = [
      path.join(app.getPath('userData'), '.cli-proxy-api'),
      path.join(os.homedir(), '.cli-proxy-api')
    ]

    for (const legacyDir of legacyDirs) {
      if (!fs.existsSync(legacyDir)) continue
      const entries = fs.readdirSync(legacyDir)
      for (const entry of entries) {
        if (!entry.toLowerCase().endsWith('.json')) continue
        const sourcePath = path.join(legacyDir, entry)
        const targetPath = path.join(authDir, entry)
        if (fs.existsSync(targetPath)) continue
        try {
          fs.copyFileSync(sourcePath, targetPath)
        } catch (e) {
          console.warn('[ProxyService] Failed to migrate auth file:', sourcePath, e)
        }
      }
    }
  }

  private hasAuthJsonFiles(dir: string): boolean {
    try {
      return fs.readdirSync(dir).some((entry) => entry.toLowerCase().endsWith('.json'))
    } catch {
      return false
    }
  }

  getConfigPath(): string {
    return this.configPath
  }

  async generateConfig(portOverride?: number) {
    const settings = this.settingsService.getSettings()
    const port = portOverride || 8317
    const authDir = this.getAuthWorkDir().replace(/\\/g, '/')
    const proxyKey = this.getProxyKey()

    // Basic Config
    let configContent = `# Auto-generated by Orbit
host: "127.0.0.1"
port: ${port}
auth-dir: "${authDir}"
api-keys:
  - "${proxyKey}" # Key for Orbit to connect to Proxy

remote-management:
  allow-remote: false
  secret-key: "orbit-management-key" # Fixed key for local management
  disable-control-panel: true
  panel-github-repository: ""

debug: true
logging-to-file: false
usage-statistics-enabled: true
request-log: true
`

    // Copilot / Codex Config
    if (settings.github?.token) {
      configContent += `
# Codex API keys (GitHub Copilot)
codex-api-key:
  - api-key: "${settings.github.token}"
    base-url: "https://api.githubcopilot.com" 
    models:
      - name: "gpt-4"
        alias: "gpt-4"
      - name: "gpt-4o"
        alias: "gpt-4o"
      - name: "gpt-4-turbo"
        alias: "gpt-4-turbo"
      - name: "claude-3.5-sonnet"
        alias: "claude-3.5-sonnet"
      - name: "o1"
        alias: "o1"
      - name: "o1-preview"
        alias: "o1-preview"
      - name: "o1-mini"
        alias: "o1-mini"
      - name: "gpt-3.5-turbo"
        alias: "gpt-3.5-turbo"
      - name: "gpt-5-codex"
        alias: "gpt-5-codex"
      - name: "gpt-5.1-codex"
        alias: "gpt-5.1-codex"
`
    }

    if (settings.anthropic?.apiKey) {
      configContent += `
# Claude API keys
claude-api-key:
  - api-key: "${settings.anthropic.apiKey}"
`
    }

    if (settings.gemini?.apiKey) {
      configContent += `
# Gemini API keys
gemini-api-key:
  - api-key: "${settings.gemini.apiKey}"
`
    }

    // OpenAI via Compatibility or dedicated if supported
    if (settings.openai?.apiKey) {
      configContent += `
# OpenAI Compatibility (Standard OpenAI)
openai-compatibility:
  - name: "openai"
    base-url: "https://api.openai.com/v1"
    api-key-entries:
      - api-key: "${settings.openai.apiKey}"
    models:
      - name: "gpt-4o"
        alias: "openai-gpt-4o"
      - name: "gpt-3.5-turbo"
        alias: "openai-gpt-3.5-turbo"
      - name: "o1-mini"
        alias: "openai-o1-mini"
`
    }

    const configDir = path.dirname(this.configPath)
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true })
    }

    fs.writeFileSync(this.configPath, configContent)
  }

  async getAntigravityAuthUrl(): Promise<{ url: string, state: string }> {
    return this.makeRequest('/v0/management/antigravity-auth-url?is_webui=true')
  }

  async getGeminiAuthUrl(): Promise<{ url: string, state: string }> {
    return this.makeRequest('/v0/management/gemini-cli-auth-url?is_webui=true')
  }

  async getClaudeAuthUrl(): Promise<{ url: string, state: string }> {
    return this.getAnthropicAuthUrl()
  }

  async getCodexAuthUrl(): Promise<{ url: string, state: string }> {
    return this.makeRequest('/v0/management/codex-auth-url?is_webui=true')
  }

  async getAnthropicAuthUrl(): Promise<{ url: string, state: string }> {
    return this.makeRequest('/v0/management/anthropic-auth-url?is_webui=true')
  }

  async getAuthFiles(): Promise<any> {
    return this.makeRequest('/v0/management/auth-files')
  }

  async downloadAuthFile(name: string): Promise<any> {
    const encoded = encodeURIComponent(name)
    return this.makeRequest(`/v0/management/auth-files/download?name=${encoded}`)
  }

  async getModels(): Promise<any> {
    const settings = this.settingsService.getSettings()
    if (settings.proxy?.enabled === false) {
      return { data: [] }
    }
    const apiKey = this.getProxyKey()
    const baseResponse = await this.makeRequest('/v1/models', apiKey)
    const baseModels = Array.isArray(baseResponse?.data) ? baseResponse.data : []

    let extraModels: any[] = []
    try {
      extraModels = await this.getAntigravityAvailableModels()
    } catch (e) {
      // Non-fatal; fall back to base list
    }

    if (extraModels.length === 0) {
      return baseResponse
    }

    const existing = new Set(baseModels.map((m: any) => m?.id).filter(Boolean))
    const merged = [...baseModels]
    for (const model of extraModels) {
      if (!existing.has(model.id)) {
        merged.push(model)
        existing.add(model.id)
      }
    }

    return { ...baseResponse, data: merged }
  }

  async getQuota(): Promise<any> {
    try {
      // 1. Get Auth Data from file
      let authData = await this.getAntigravityAuthData()
      if (!authData) return null

      // 2. Check Expiry and Refresh if needed
      if (this.isTokenExpired(authData.expired)) {
        console.log('[ProxyService] Token expired, refreshing...')
        const newToken = await this.refreshAntigravityToken(authData.refresh_token)
        if (newToken) {
          authData.access_token = newToken.access_token
          authData.expired = newToken.expired
          // Save back to file (optional but good for syncing)
          await this.updateAuthFile(authData)
        } else {
          console.error('[ProxyService] Failed to refresh token')
          return null // Cannot proceed
        }
      }

      // 3. Fetch Quota from Google Cloud API
      const endpoints = [
        'https://daily-cloudcode-pa.googleapis.com/v1internal:fetchAvailableModels',
        'https://daily-cloudcode-pa.sandbox.googleapis.com/v1internal:fetchAvailableModels',
        'https://cloudcode-pa.googleapis.com/v1internal:fetchAvailableModels'
      ]

      for (const endpoint of endpoints) {
        try {
          const response = await axios.post(
            endpoint,
            {},
            {
              headers: {
                'Authorization': `Bearer ${authData.access_token}`,
                'Content-Type': 'application/json',
                'User-Agent': 'antigravity/1.104.0 darwin/arm64' // Mimic extension
              },
              timeout: 5000
            }
          )

          if (response.status === 200 && response.data) {
            return this.parseQuotaResponse(response.data)
          }
        } catch (e: any) {
          // If 403, might be banned or token invalid
          if (e.response?.status === 403) {
            console.warn(`[ProxyService] 403 Forbidden at ${endpoint}`)
            break // Don't retry other endpoints if forbidden
          }
          // Continue to next endpoint
          console.warn(`[ProxyService] Endpoint failed: ${endpoint}`, e.message)
        }
      }

      return null
    } catch (error: any) {
      console.error('[ProxyService] Failed to fetch quota:', error)
      return null
    }
  }

  // --- Helper Methods ---

  private async getAntigravityAuthData(): Promise<any | null> {
    try {
      const authDir = this.getAuthWorkDir()
      if (!fs.existsSync(authDir)) return null

      const files = fs.readdirSync(authDir)
      const antigravityFiles = files.filter(f => f.startsWith('antigravity-') && f.endsWith('.json'))

      if (antigravityFiles.length === 0) return null

      // Find the most recently modified file
      const recentFile = antigravityFiles.map(f => ({
        name: f,
        path: path.join(authDir, f),
        mtime: fs.statSync(path.join(authDir, f)).mtimeMs
      })).sort((a, b) => b.mtime - a.mtime)[0]

      const content = fs.readFileSync(recentFile.path, 'utf8')
      const data = JSON.parse(content)
      return { ...data, _filePath: recentFile.path } // attach path for updates
    } catch (e) {
      console.error('[ProxyService] Error reading auth file:', e)
      return null
    }
  }

  private async getAntigravityAvailableModels(): Promise<any[]> {
    try {
      let authData = await this.getAntigravityAuthData()
      if (!authData) return []

      if (this.isTokenExpired(authData.expired)) {
        const newToken = await this.refreshAntigravityToken(authData.refresh_token)
        if (newToken) {
          authData.access_token = newToken.access_token
          authData.expired = newToken.expired
          await this.updateAuthFile(authData)
        } else {
          return []
        }
      }

      const endpoints = [
        'https://daily-cloudcode-pa.googleapis.com/v1internal:fetchAvailableModels',
        'https://daily-cloudcode-pa.sandbox.googleapis.com/v1internal:fetchAvailableModels',
        'https://cloudcode-pa.googleapis.com/v1internal:fetchAvailableModels'
      ]

      for (const endpoint of endpoints) {
        try {
          const response = await axios.post(
            endpoint,
            {},
            {
              headers: {
                'Authorization': `Bearer ${authData.access_token}`,
                'Content-Type': 'application/json',
                'User-Agent': 'antigravity/1.104.0 darwin/arm64'
              },
              timeout: 5000
            }
          )

          if (response.status === 200 && response.data?.models) {
            const models: any[] = []
            for (const [key, val] of Object.entries(response.data.models) as any) {
              if (!val || key.startsWith('chat_') || key.startsWith('rev')) continue
              models.push({
                id: key,
                name: key,
                owned_by: 'antigravity'
              })
            }
            return models
          }
        } catch (e: any) {
          if (e.response?.status === 403) break
        }
      }

      return []
    } catch {
      return []
    }
  }

  private isTokenExpired(expiredStr?: string): boolean {
    if (!expiredStr) return true
    return new Date(expiredStr).getTime() < Date.now()
  }

  private async refreshAntigravityToken(refreshToken?: string): Promise<{ access_token: string, expired: string } | null> {
    if (!refreshToken) return null
    try {
      const params = new URLSearchParams()
      params.append('client_id', '1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com')
      params.append('client_secret', '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')
      params.append('refresh_token', refreshToken)
      params.append('grant_type', 'refresh_token')

      const res = await axios.post('https://oauth2.googleapis.com/token', params, {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }
      })

      if (res.data && res.data.access_token) {
        const expired = new Date(Date.now() + (res.data.expires_in || 3600) * 1000).toISOString()
        return { access_token: res.data.access_token, expired }
      }
      return null
    } catch (e: any) {
      console.error('[ProxyService] Token refresh failed:', e.response?.data || e.message)
      return null
    }
  }

  private async updateAuthFile(data: any) {
    if (data._filePath) {
      try {
        const { _filePath, ...content } = data
        fs.writeFileSync(_filePath, JSON.stringify(content, null, 2))
      } catch (e) {
        console.error('[ProxyService] Failed to update auth file:', e)
      }
    }
  }

  private parseQuotaResponse(data: any): any {
    // Map Google API response to our UI format
    if (!data.models) return null

    const models = []

    // Known display names mapping
    const nameMap: Record<string, string> = {
      "gemini-2.5-pro": "Gemini 2.5 Pro",
      "gemini-2.5-flash": "Gemini 2.5 Flash",
      "gemini-2.0-flash": "Gemini 2.0 Flash",
      "gemini-exp-1206": "Gemini Exp",
      "claude-sonnet-4-5": "Claude Sonnet 4.5",
      "claude-opus-4-5": "Claude Opus 4.5"
    }

    for (const [key, val] of Object.entries(data.models) as any) {
      if (val && val.quotaInfo) {
        // Filter noise models (chat_*, rev*)
        if (key.startsWith('chat_') || key.startsWith('rev')) continue

        const remaining = val.quotaInfo.remainingFraction || 0
        models.push({
          name: nameMap[key] || key,
          percentage: Math.round(remaining * 100),
          reset: new Date(val.quotaInfo.resetTime).toLocaleString('tr-TR', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
        })
      }
    }

    return {
      remaining_credits: models.length > 0 ? `${Math.round(models.reduce((a, b: any) => a + b.percentage, 0) / models.length)}%` : 'Available',
      next_reset: models.length > 0 ? models[0].reset : '-',
      models: models.sort((a: any, b: any) => a.name.localeCompare(b.name))
    }
  }

  private makeRequest(path: string, apiKey: string = 'orbit-management-key'): Promise<any> {
    return new Promise((resolve, reject) => {
      const { net } = require('electron')
      const request = net.request({
        method: 'GET',
        protocol: 'http:',
        hostname: '127.0.0.1',
        port: 8317,
        path: path
      })

      request.setHeader('Authorization', `Bearer ${apiKey}`)

      request.on('response', (response: Electron.IncomingMessage) => {
        let data = ''
        response.on('data', (chunk: Buffer) => data += chunk)
        response.on('end', () => {
          try {
            if (response.statusCode && response.statusCode >= 200 && response.statusCode < 300) {
              resolve(JSON.parse(data))
            } else {
              reject(new Error(`Request failed with status ${response.statusCode}: ${data}`))
            }
          } catch (e) {
            reject(e)
          }
        })
      })

      request.on('error', (error: Error) => reject(error))
      request.end()
    })
  }

  // --- Copilot Quota ---

  async getCopilotQuota(): Promise<any> {
    try {
      // 1. Get GitHub token from settings (saved during GitHub login)
      const settings = this.settingsService.getSettings()
      const token = settings.github?.token
      if (!token || token === 'connected') {
        console.log('[ProxyService] No GitHub token found')
        return null
      }

      // 2. Get username from GitHub API
      let username: string | null = null
      try {
        const userRes = await axios.get('https://api.github.com/user', {
          headers: {
            'Authorization': `Bearer ${token}`,
            'Accept': 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28'
          }
        })
        username = userRes.data?.login
      } catch (e: any) {
        console.error('[ProxyService] Failed to get GitHub username:', e.response?.status, e.message)
        if (e.response?.status === 401) {
          return { error: 'invalid_token', message: 'GitHub token is invalid or expired' }
        }
        return null
      }

      if (!username) return null

      // 3. Fetch premium request usage
      const now = new Date()
      const year = now.getFullYear()
      const month = now.getMonth() + 1

      const response = await axios.get(
        `https://api.github.com/users/${username}/settings/billing/premium_request/usage?year=${year}&month=${month}`,
        {
          headers: {
            'Authorization': `Bearer ${token}`,
            'Accept': 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28'
          },
          timeout: 10000
        }
      )

      if (response.status === 200 && response.data) {
        return this.parseCopilotQuotaResponse(response.data, username)
      }

      return null
    } catch (e: any) {
      console.error('[ProxyService] Copilot quota fetch failed:', e.response?.status, e.response?.data || e.message)
      // If 403, the token doesn't have billing permissions
      if (e.response?.status === 403) {
        return { error: 'permission_denied', message: 'Token needs "Plan" permission' }
      }
      return null
    }
  }

  private parseCopilotQuotaResponse(data: any, username: string): any {
    // Parse the GitHub billing response
    const usageItems = data.usageItems || []

    // Calculate total usage this month
    let totalUsed = 0
    const models: any[] = []

    for (const item of usageItems) {
      if (item.product === 'Copilot') {
        totalUsed += item.netQuantity || 0
        models.push({
          name: item.model || 'Unknown',
          quantity: item.netQuantity || 0,
          amount: item.netAmount || 0
        })
      }
    }

    // Premium entitlement is typically 300/month for Pro users
    const monthlyLimit = 300
    const remaining = Math.max(0, monthlyLimit - totalUsed)
    const percentage = Math.round((remaining / monthlyLimit) * 100)

    return {
      username,
      used: totalUsed,
      limit: monthlyLimit,
      remaining,
      percentage,
      models,
      period: data.timePeriod
    }
  }

  async getCodexUsage(): Promise<any> {
    const result: any = {}
    let authEntry: any = null
    try {
      const status = await this.getAuthFiles()
      const files = Array.isArray(status?.files) ? status.files : []
      authEntry = files.find((file: any) => {
        const provider = String(file?.provider || file?.type || '').toLowerCase()
        return provider === 'codex' || provider === 'openai'
      })

      if (authEntry) {
        if (authEntry.email) result.email = authEntry.email
        if (authEntry.id_token) {
          result.planType = authEntry.id_token.plan_type || authEntry.id_token.chatgpt_plan_type
          result.accountId = authEntry.id_token.chatgpt_account_id || authEntry.id_token.account_id
        }
      }
    } catch (e) {
      // Non-fatal; auth metadata may be unavailable
    }

    if (authEntry?.name) {
      try {
        const authData = await this.downloadAuthFile(authEntry.name)
        const accessToken = this.pickOpenAiAccessToken(authData)
        if (accessToken) {
          const whamData = await this.fetchCodexUsageFromWham(accessToken)
          const whamUsage = this.extractCodexUsageFromWham(whamData)
          if (whamUsage) {
            result.usage = whamUsage
            result.usageSource = 'chatgpt'
          }
        }
      } catch (e) {
        // Non-fatal; usage may be unavailable
      }
    }

    try {
      const usageResponse = await this.makeRequest('/v0/management/usage')
      const usage = this.extractCodexUsage(usageResponse?.usage)
      if (usage) {
        if (result.usage) {
          result.usage = { ...usage, ...result.usage }
        } else {
          result.usage = usage
          result.usageSource = 'proxy'
        }
      }
    } catch (e) {
      // Non-fatal; usage stats may be disabled
    }

    return result
  }

  private pickOpenAiAccessToken(authData: any): string | null {
    const candidates = [
      authData?.access_token,
      authData?.accessToken,
      authData?.AccessToken,
      authData?.token?.access_token,
      authData?.token?.accessToken,
      authData?.session?.access_token,
      authData?.session?.accessToken,
      authData?.auth?.access_token,
      authData?.auth?.accessToken
    ]

    for (const value of candidates) {
      if (typeof value === 'string' && value.trim()) {
        return value.trim()
      }
    }
    return null
  }

  private async fetchCodexUsageFromWham(accessToken: string): Promise<any | null> {
    const endpoints = [
      'https://chatgpt.com/backend-api/wham/usage',
      'https://chat.openai.com/backend-api/wham/usage'
    ]

    for (const endpoint of endpoints) {
      try {
        const response = await axios.get(endpoint, {
          headers: {
            Authorization: `Bearer ${accessToken}`,
            Accept: 'application/json'
          },
          timeout: 10000
        })
        if (response?.data) {
          return response.data
        }
      } catch (e: any) {
        const status = e?.response?.status
        if (status === 401 || status === 403) {
          break
        }
        console.warn('[ProxyService] Codex usage endpoint failed:', endpoint, e?.message || e)
      }
    }

    return null
  }

  private extractCodexUsageFromWham(data: any): {
    totalRequests?: number
    totalTokens?: number
    remainingRequests?: number
    remainingTokens?: number
    resetAt?: string
    dailyUsage?: number
    dailyLimit?: number
    weeklyUsage?: number
    weeklyLimit?: number
    dailyUsedPercent?: number
    weeklyUsedPercent?: number
    dailyResetAt?: string
    weeklyResetAt?: string
  } | null {
    if (!data || typeof data !== 'object') return null

    const totalRequests = this.findNumberByKeys(data, [
      'total_requests',
      'totalRequests',
      'request_count',
      'requests_used',
      'requests'
    ])
    const totalTokens = this.findNumberByKeys(data, [
      'total_tokens',
      'totalTokens',
      'token_count',
      'tokens_used',
      'tokens'
    ])
    const remainingRequests = this.findNumberByKeys(data, [
      'remaining_requests',
      'remainingRequests',
      'requests_remaining'
    ])
    const remainingTokens = this.findNumberByKeys(data, [
      'remaining_tokens',
      'remainingTokens',
      'tokens_remaining'
    ])
    const dailyUsage = this.findNumberByKeys(data, [
      'daily_usage',
      'dailyUsage',
      'daily_used',
      'usage_daily',
      'requests_daily',
      'requests_today'
    ])
    const dailyLimit = this.findNumberByKeys(data, [
      'daily_limit',
      'dailyLimit',
      'limit_daily',
      'daily_quota'
    ])
    const weeklyUsage = this.findNumberByKeys(data, [
      'weekly_usage',
      'weeklyUsage',
      'weekly_used',
      'usage_weekly',
      'requests_weekly'
    ])
    const weeklyLimit = this.findNumberByKeys(data, [
      'weekly_limit',
      'weeklyLimit',
      'limit_weekly',
      'weekly_quota'
    ])
    const dailyUsedPercent = this.findNumberByKeys(data, [
      'rate_limit.primary_window.used_percent',
      'rate_limit.primary_window.usedPercent'
    ])
    const weeklyUsedPercent = this.findNumberByKeys(data, [
      'rate_limit.secondary_window.used_percent',
      'rate_limit.secondary_window.usedPercent'
    ])
    const dailyResetAt = this.normalizeResetAt(
      this.findNumberByKeys(data, [
        'rate_limit.primary_window.reset_at',
        'rate_limit.primary_window.resetAt'
      ])
    )
    const weeklyResetAt = this.normalizeResetAt(
      this.findNumberByKeys(data, [
        'rate_limit.secondary_window.reset_at',
        'rate_limit.secondary_window.resetAt'
      ])
    )
    const resetAt = this.normalizeResetAt(
      this.findStringByKeys(data, [
        'reset_at',
        'resetAt',
        'reset_time',
        'resetTime',
        'next_reset',
        'renew_at',
        'renewAt'
      ]) ?? this.findNumberByKeys(data, [
        'reset_at',
        'resetAt',
        'reset_time',
        'resetTime',
        'next_reset',
        'renew_at',
        'renewAt'
      ])
    )

    if (
      totalRequests === null &&
      totalTokens === null &&
      remainingRequests === null &&
      remainingTokens === null &&
      dailyUsage === null &&
      dailyLimit === null &&
      weeklyUsage === null &&
      weeklyLimit === null &&
      dailyUsedPercent === null &&
      weeklyUsedPercent === null &&
      !dailyResetAt &&
      !weeklyResetAt &&
      !resetAt
    ) {
      return null
    }

    return {
      ...(totalRequests !== null ? { totalRequests } : {}),
      ...(totalTokens !== null ? { totalTokens } : {}),
      ...(remainingRequests !== null ? { remainingRequests } : {}),
      ...(remainingTokens !== null ? { remainingTokens } : {}),
      ...(dailyUsage !== null ? { dailyUsage } : {}),
      ...(dailyLimit !== null ? { dailyLimit } : {}),
      ...(weeklyUsage !== null ? { weeklyUsage } : {}),
      ...(weeklyLimit !== null ? { weeklyLimit } : {}),
      ...(dailyUsedPercent !== null ? { dailyUsedPercent } : {}),
      ...(weeklyUsedPercent !== null ? { weeklyUsedPercent } : {}),
      ...(dailyResetAt ? { dailyResetAt } : {}),
      ...(weeklyResetAt ? { weeklyResetAt } : {}),
      ...(resetAt ? { resetAt } : {})
    }
  }

  private findNumberByKeys(root: any, keys: string[]): number | null {
    const queue: Array<{ value: any; depth: number }> = [{ value: root, depth: 0 }]
    while (queue.length > 0) {
      const current = queue.shift()
      if (!current) continue
      const { value, depth } = current
      if (!value || typeof value !== 'object') continue

      if (!Array.isArray(value)) {
        for (const key of keys) {
          if (key.includes('.')) {
            const path = key.split('.')
            let cursor = value
            let found = true
            for (const part of path) {
              if (!cursor || typeof cursor !== 'object' || !(part in cursor)) {
                found = false
                break
              }
              cursor = cursor[part]
            }
            if (found) {
              const num = this.toNumber(cursor)
              if (num !== null) return num
            }
            continue
          }
          if (Object.prototype.hasOwnProperty.call(value, key)) {
            const num = this.toNumber(value[key])
            if (num !== null) return num
          }
        }
      }

      if (depth >= 4) continue
      const children = Array.isArray(value) ? value : Object.values(value)
      for (const child of children) {
        if (child && typeof child === 'object') {
          queue.push({ value: child, depth: depth + 1 })
        }
      }
    }
    return null
  }

  private findStringByKeys(root: any, keys: string[]): string | null {
    const queue: Array<{ value: any; depth: number }> = [{ value: root, depth: 0 }]
    while (queue.length > 0) {
      const current = queue.shift()
      if (!current) continue
      const { value, depth } = current
      if (!value || typeof value !== 'object') continue

      if (!Array.isArray(value)) {
        for (const key of keys) {
          if (Object.prototype.hasOwnProperty.call(value, key)) {
            const candidate = value[key]
            if (typeof candidate === 'string' && candidate.trim()) {
              return candidate.trim()
            }
          }
        }
      }

      if (depth >= 4) continue
      const children = Array.isArray(value) ? value : Object.values(value)
      for (const child of children) {
        if (child && typeof child === 'object') {
          queue.push({ value: child, depth: depth + 1 })
        }
      }
    }
    return null
  }

  private toNumber(value: any): number | null {
    if (typeof value === 'number' && Number.isFinite(value)) {
      return value
    }
    if (typeof value === 'string') {
      const trimmed = value.trim()
      if (!trimmed) return null
      const parsed = Number(trimmed)
      if (!Number.isNaN(parsed)) return parsed
    }
    return null
  }

  private normalizeResetAt(value: any): string | null {
    if (typeof value === 'string' && value.trim()) {
      return value.trim()
    }
    const numeric = this.toNumber(value)
    if (numeric === null) return null
    const ms = numeric < 1_000_000_000_000 ? numeric * 1000 : numeric
    return new Date(ms).toISOString()
  }

  private extractCodexUsage(snapshot: any): { totalRequests: number; totalTokens: number } | null {
    if (!snapshot || typeof snapshot !== 'object') return null
    const apis = snapshot.apis || snapshot.APIs
    if (!apis || typeof apis !== 'object') return null

    let totalRequests = 0
    let totalTokens = 0
    let matched = false

    for (const [apiKey, apiStats] of Object.entries(apis as Record<string, any>)) {
      if (!apiStats || typeof apiStats !== 'object') continue

      const models = apiStats.models || apiStats.Models
      let modelMatched = false

      if (models && typeof models === 'object') {
        for (const [modelName, modelStats] of Object.entries(models as Record<string, any>)) {
          const name = String(modelName).toLowerCase()
          if (!name.includes('codex')) continue
          totalRequests += Number(modelStats?.total_requests || modelStats?.TotalRequests || 0)
          totalTokens += Number(modelStats?.total_tokens || modelStats?.TotalTokens || 0)
          modelMatched = true
        }
      }

      if (!modelMatched) {
        const key = String(apiKey).toLowerCase()
        if (key.includes('codex')) {
          totalRequests += Number(apiStats?.total_requests || apiStats?.TotalRequests || 0)
          totalTokens += Number(apiStats?.total_tokens || apiStats?.TotalTokens || 0)
          modelMatched = true
        }
      }

      if (modelMatched) matched = true
    }

    if (!matched) return null
    return { totalRequests, totalTokens }
  }
}
